---
title: "Manual for using and maintaining the Oceans Monitoring, Evaluation & Learning Dashboard"
output: 
rmarkdown::html_vignette:
   toc: true
    number_sections: false
vignette: >
  %\VignetteIndexEntry{User_Manual}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


The Oceans Dashboard is an interactive application that displays indicator time-series data to monitor progress towards goals for nature, people, and climate. It has been developed as an R package {OceansDash} to facilitate robust documentation and long-term maintenance of the application. 

You can run the application locally via:

``` r
library(OceansDash)
run_app()
```

## Table of contents

This manual provides instructions for:

1) editing the application user-interface and server code base [**here**](#instructions-for-editing-the-application-user-interface-and-server-codebase), and
2) updating indicator data displayed in the application [**here**](#instructions-for-updating-indicator-data-displayed-in-the-application).

## Instructions for editing the application user-interface and server codebase

To begin editing or updating the application:

1. [Fork and clone](https://happygitwithr.com/fork-and-clone) the [github repository](https://github.com/cabuelow/OceansDash) or, if you already have a local {OceansDash} github repository, navigate to the folder on your computer and double-click on the .Rproj file `OceansDash.Rproj`
2. Start a new [development branch](https://happygitwithr.com/git-branches.html?q=branch#create-a-new-branch) in github
3. Make edits to scripts and files - pull, commit and push regularly to your development branch. Click [**here**](#making-edits) for more information on how to edit.
4. When your edits are complete, make a [pull request](https://happygitwithr.com/pr-extend.html?q=pull%20request#pr-extend) and merge with the remote github repository if there are no conflicts.

### Making edits

There are three main folders to be aware of to edit...

*As you can see, there are many other files in the {OceansDash} package that are not discussed here. Those not mentioned are not neccesary for app development, but you can find more information on what they do/how to use them [here](https://engineering-shiny.org/build-app-golem.html)*

2. Opening the **'dev/02_dev.R'** script. 
- This is where you can: 
  - A) add packages, 
  - B) add modules, and 
  - C) add ‘business’ logic (as opposed to application logic) in the form of of functions (add_fct) or utilities (add_utils) - the latter being smaller functions that will be used several times. [Read more here](https://engineering-shiny.org/build-app-golem.html)

3. Opening the **'data-raw/make-sysdata.R'** script.
- Here you can import and wrangle processed indicator data to be used internally by the app. Make sure to add it to the 'sysdata.rda' at the bottom of the script. Run through all lines of code in the script to update all internal datasets and overwrite the current 'sysdata.rda'.

4. Opening the **'R/'** folder.
- Here you will find the following R scripts and files:
  - A) The `app_ui.R` and `app_server.R` files that serve to provide the main app structure and integrate modules,
  - B) Any modules (aka 'sub-apps', e.g., `mod_main.R`), and
  - C) The `sysdata.rda` file created via Step 2 above
  
5. Once you have made changes to any of the above, you can test your edits by running the development version of the app via:

``` r
golem::run_dev()
```

6. If you want to deploy the app to a shinyapps.io server, run the development version as above and hit 'Publish' on the top right corner of the app as it is running.

## Instructions for updating indicator data displayed in the application

All scripts for processing indicator data are located in the **'data-raw/process-indicators/'** folder. Instructions for downloading data and processing the indicators are provided below, organised such that indicators derived from the same data source are described together.

#### Indicators derived from the Ocean Health Index: Marine Red List | Fisheries Stock Condition (OHI Fisheries (subgoal) indicator) | Habitat Condition (OHI Habitat (subgoal) indicator) | Carbon storage (OHI Carbon storage indicator)

The *Marine Red List*, *Fisheries Stock Condition*, *Habitat Condition*, and *Carbon Storage* indicators are all sourced from the [Ocean Health Index](https://oceanhealthindex.org/).

Note that data is not available for Alaska.

Citation: Ocean Health Index. 2024. ohi-global version: Global scenarios data for Ocean Health Index, [August 26, 2024]. National Center for Ecological Analysis and Synthesis, University of California, Santa Barbara. Available at: https://github.com/OHI-Science/ohi-global/releases

The *Marine Red List* indicator is the [Ocean Health Index Biodiversity (Species sub-goal) indicator](https://oceanhealthindex.org/global-scores/goal-scores/biodiversity/species/). A high score indicates that most native marine species in a country are not identified as threatened or vulnerable by the IUCN which monitors the status of many species.

The *Fisheries Stock Condition* indicator is the [Ocean Health Index Food Provision (Wild Caught Fisheries subgoal) indicator](https://oceanhealthindex.org/global-scores/goal-scores/food-provision/wild-caught-fisheries/). It measures ability to sustainably maximize wild-caught fisheries.

The *Habitat Condition* indicator is the [Ocean Health Index Biodiversity (Habitat sub-goal) indicator](https://oceanhealthindex.org/goals/biodiversity/habitats/). This goal assesses the condition of marine habitats that are particularly important in supporting large numbers of marine species. The status of each habitat is its current condition relative to its reference condition, which is often based on historical area. A score of 1 indicates that the condition equals or exceeds the reference point. The subgoal score is then calculated by combining the habitat scores for each region.

The *Carbon Storage* indicator is the [Ocean Health Index Carbon storage indicator](https://oceanhealthindex.org/global-scores/goal-scores/carbon-storage/). It captures the ability of coastal habitats to store carbon given the amount of carbon they store and their health.

To update these indicators:
1) download the most recent indicator scores [here](https://oceanhealthindex.org/global-scores/data-download/),
2) place the downloaded folder in **'data-raw/process-indicators/data-downloaded/ocean-health-index'**,
3) run the R script **'data-raw/process-indicators/scripts/ocean-health-index.R'** to process the indicator,
4) if you are updating other indicators, do that first before then running the R script **'data-raw/process-indicators/export-processed-indicators.R'**.

#### Ecosystem indicators

Ecosystem extent and carbon storage under effective protection are calculated for mangroves, saltmarsh, and coral reef ecosystems (with the exception of carbon storage for coral reefs as global data is not currently available). Global mapping of seagrass and kelp forest ecosystem extent is not of high enough resolution to estimate their effective protection, but can be included when data becomes available.

To update these indicators, 
1) download and clean the World Database of Protected Areas....
2) 

Download data: ....

#### Marine Living Planet Index

The *Marine Living Planet Index* measures trends in marine species populations through time. Index values represent the average rate of change in populations. It is calculated for marine species in each country via the following [*Living Planet Index*](https://www.livingplanetindex.org/) methodology.

Citation: LPI 2024. Living Planet Index database. 2024. < www.livingplanetindex.org/>. Downloaded on 30 August 2024

To update this indicator: 
1) download the most recent data [**here**](https://www.livingplanetindex.org/data_portal),
2) place the downloaded data folder in: **'data-raw/process-indicators/data-downloaded/marine-living-planet-index'**,
3) run the R script **'data-raw/process-indicators/scripts/marine-living-planet-index.R'** to process the indicator for each country,
4) if you are updating other indicators, do that first before then running an R script that combines all of the processed indicators into a single dataframe that can be used in the dashboard application: **'data-raw/process-indicators/export-processed-indicators.R'**.

#### Small-scale fisheries rights

Degree of application of a legal/regulatory/policy/institutional framework which recognizes and protects access rights for small-scale fisheries that is updated biannually. The indicator score refers to the level of implementation: 1 (lowest) to 5 (highest).

Note there is no data available for Alaska, Mozambique, Papua New Guinea, or Madagascar.

Citation: Data from multiple sources compiled by the UN – processed by Our World in Data. “14.b.1 - Degree of application of a legal/regulatory/policy/institutional framework which recognizes and protects access rights for small-scale fisheries (level of implementation: 1 lowest to 5 highest) - ER_REG_SSFRAR” [dataset]. Data from multiple sources compiled by the UN [original data].

To update this indicator: 
1) download the most recent data [**here**](https://ourworldindata.org/sdgs/life-below-water#sdg-indicator-14-b-1-support-small-scale-fishers),
2) place the downloaded .csv file in: **'data-raw/process-indicators/data-downloaded/small-scale-fisheries-rights'**,
3) run the R script **'data-raw/process-indicators/scripts/small-scale-fisheries-rights.R'** to process the indicator for each country,
4) if you are updating other indicators, do that first before then running an R script that combines all of the processed indicators into a single dataframe that can be used in the dashboard application: **'data-raw/process-indicators/export-processed-indicators.R'**.

#### Wealth relative Index
Data source: https://sedac.ciesin.columbia.edu/data/set/povmap-grdi-v1 (Inverted Relative Deprivation Index)

#### Human Development Index
Data source: Kummu, M. et al. Gridded global datasets for Gross Domestic Product and Human Development Index over 1990–2015. Sci. Data 5:180004 doi: 10.1038/sdata.2018.4 (2018)
  
#### Climate Adaptation Plans
Data sources:....
